app = "periodo-proxy-dev"
primary_region = "iad"

[build]

[[mounts]]
  source = "cache"
  destination = "/mnt/cache"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
