# fly.toml app configuration file generated for periodo-proxy on 2023-09-12T20:59:47-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "periodo-proxy"
primary_region = "iad"

[build]

[[mounts]]
  source = "cache"
  destination = "/mnt/cache"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
